Added many websites
OhMyGuus/I-Still-Dont-Care-About-Cookies pull request #12709
Opened 2024-04-09 07:22 UTC by benni347

Fixed https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/6123
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12665
Fixed the error to resolve https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12679
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12520 and https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12215 duplicates because of me.
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12662
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12653
Fixes: https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12661
fixes the error to resolve https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10739
Fixed https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10688
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12641
Fixed the grey overlay to resolve https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10766.
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12643
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12664
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12656
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12658
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/11496
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10807 the page had a grey background on visit.
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/5992
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12649
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12654
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12646
resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10790
Fixes https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12652
Fixed https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10815
Fixed https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/6123

Duplicates below:
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/12441
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/11423
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/11160
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/8263
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/11052
Resolves https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/11496

2024-06-15 15:08 UTC, obfuscated-loop requested changes
Please fix requests, other than that, looks good to merge and thanks for your help! :+1:

2024-06-15 15:08 UTC, obfuscated-loop commented on src/data/js/5_clickHandler.js
> +      return '._5r2nlf4';
Shouldn't be a randomly generated ID, use `#redesignCmpWrapper a[href="https://as.com/"]` as it should remain static.

2024-06-15 18:46 UTC, obfuscated-loop commented
I have force pushed the fixes to your branch. Thanks again. Merging.

2024-06-15 18:46 UTC, obfuscated-loop approved these changes

2024-06-15 18:46 UTC, merged

2024-11-04 22:36 UTC, thibaultmol commented
Are these also not solved? 
![image](https://github.com/user-attachments/assets/5ab17654-40e6-4ce3-bb95-1254454234f4)